In [2]:
import os
import time
import uuid
import pandas as pd
import fitz  # PyMuPDF
from typing import Optional
from pydantic import BaseModel, Field
from docling.document_converter import DocumentConverter

# Enable async execution in Jupyter (Needed if you use LlamaParse)
import nest_asyncio
nest_asyncio.apply()
from llama_parse import LlamaParse

class NCCNChunkMetadata(BaseModel):
    source: str = Field(..., description="File path or URL of the guideline")
    page: int = Field(..., description="Page number of the chunk")
    document_type: str = Field(default="Clinical Guideline", description="Type of document")
    publication_date: str = Field(..., description="Year of publication")
    section: Optional[str] = Field(None, description="Guideline section/heading")
    chunk_id: str = Field(default_factory=lambda: str(uuid.uuid4()), description="Unique identifier")

class DocumentChunk(BaseModel):
    text: str
    metadata: NCCNChunkMetadata

/tmp/ipykernel_64689/3832774614.py:13: DeprecationWarning: The 'llama-parse' package is deprecated and will no longer receive updates. Please migrate to the new unified SDK. See https://developers.llamaindex.ai/python/cloud/llamaparse/getting_started/ and https://github.com/run-llama/llama-cloud-py/blob/main/README.md for migration instructions.
  from llama_parse import LlamaParse

In [3]:
class AdvancedIngestionPipeline:
    def __init__(self):
        # Initialize Docling for local structural and tabular parsing
        self.docling_converter = DocumentConverter()
        
        # Initialize LlamaParse requesting strict markdown output
        self.llama_parser = LlamaParse(
            result_type="markdown",
            verbose=True
        )

    def process_pymupdf(self, file_path: str, year: str) -> dict:
        """Baseline extraction: Fast, but loses complex table relationships."""
        start_time = time.time()
        doc = fitz.open(file_path)
        chunks = []
        
        for page_num, page in enumerate(doc):
            text = page.get_text("text").strip()
            if text:
                meta = NCCNChunkMetadata(
                    source=file_path, 
                    page=page_num + 1,
                    publication_date=year
                )
                chunks.append(DocumentChunk(text=text, metadata=meta))
                
        return {
            "method": "PyMuPDF", 
            "time_seconds": time.time() - start_time, 
            "chunks": chunks
        }

    def process_docling(self, file_path: str, year: str) -> dict:
        """Advanced local extraction: Preserves reading order and Markdown tables."""
        start_time = time.time()
        result = self.docling_converter.convert(file_path)
        chunks = []
        
        # Extract Standard Text
        for item in result.document.texts:
            meta = NCCNChunkMetadata(
                source=file_path, 
                page=item.prov[0].page_no if item.prov else 0,
                publication_date=year, 
                section="Standard Text"
            )
            chunks.append(DocumentChunk(text=item.text, metadata=meta))
            
        # Extract Tables as Markdown (Crucial for clinical guidelines)
        for table in result.document.tables:
            meta = NCCNChunkMetadata(
                source=file_path, 
                page=table.prov[0].page_no if table.prov else 0,
                publication_date=year, 
                section="Tabular Data"
            )
            # doc=result.document is passed to avoid deprecation warnings
            chunks.append(DocumentChunk(text=table.export_to_markdown(doc=result.document), metadata=meta))
            
        return {
            "method": "Docling", 
            "time_seconds": time.time() - start_time, 
            "chunks": chunks
        }

    def process_llamaparse(self, file_path: str, year: str) -> dict:
        """API-based extraction: Premium structural and table parsing via cloud vision models."""
        if "LLAMA_CLOUD_API_KEY" not in os.environ:
            print("Skipping LlamaParse: API Key not set in environment variables.")
            return {"method": "LlamaParse", "time_seconds": 0, "chunks": []}

        start_time = time.time()
        
        documents = self.llama_parser.load_data(file_path)
        chunks = []
        
        for doc in documents:
            blocks = doc.text.split('\n\n')
            for block in blocks:
                if block.strip():
                    meta = NCCNChunkMetadata(
                        source=file_path, 
                        page=0, 
                        publication_date=year, 
                        section="LlamaParse Block"
                    )
                    chunks.append(DocumentChunk(text=block.strip(), metadata=meta))
                    
        return {
            "method": "LlamaParse", 
            "time_seconds": time.time() - start_time, 
            "chunks": chunks
        }

In [7]:
# Set your LlamaCloud API Key if testing LlamaParse
os.environ["LLAMA_CLOUD_API_KEY"] = "llx-GTFHiS8J2S5fceKJDS6VPFfOmHcnopNtsZFkM4QBI7yoO16O"

TEST_FILE = "NCCN_Guidelines_dataset/guidelines/2023genetics_bop_3.2023_active_021323.pdf" 
YEAR = "2023"

pipeline = AdvancedIngestionPipeline()

print(f"Running PyMuPDF...")
pymupdf_results = pipeline.process_pymupdf(TEST_FILE, YEAR)

print("Running Docling (Local Document Parsing)...")
docling_results = pipeline.process_docling(TEST_FILE, YEAR)

print("Running LlamaParse (Cloud Vision API)...")
llamaparse_results = pipeline.process_llamaparse(TEST_FILE, YEAR)

# Generate Benchmark Report
df_report = pd.DataFrame([
    {"Method": "PyMuPDF", "Time (s)": round(pymupdf_results["time_seconds"], 2), "Chunks": len(pymupdf_results["chunks"])},
    {"Method": "Docling", "Time (s)": round(docling_results["time_seconds"], 2), "Chunks": len(docling_results["chunks"])},
    {"Method": "LlamaParse", "Time (s)": round(llamaparse_results["time_seconds"], 2), "Chunks": len(llamaparse_results["chunks"])}
])

display(df_report)

# Inspect output to verify table structures
print("\n--- SAMPLE DOCLING EXTRACTION ---")
if docling_results["chunks"]:
    table_chunks = [c for c in docling_results["chunks"] if c.metadata.section == "Tabular Data"]
    if table_chunks:
        print(table_chunks[0].text)

Running PyMuPDF...

[INFO] 2026-06-22 22:22:53,800 [RapidOCR] base.py:22: Using engine_name: torch
[INFO] 2026-06-22 22:22:53,801 [RapidOCR] device_config.py:64: Using GPU device with ID: 0
[INFO] 2026-06-22 22:22:53,824 [RapidOCR] download_file.py:60: File exists and is valid: /home/creo/coding/Internship/Oncology_Research_Assistant/.venv/lib/python3.12/site-packages/rapidocr/models/ch_PP-OCRv4_det_mobile.pth
[INFO] 2026-06-22 22:22:53,824 [RapidOCR] main.py:50: Using /home/creo/coding/Internship/Oncology_Research_Assistant/.venv/lib/python3.12/site-packages/rapidocr/models/ch_PP-OCRv4_det_mobile.pth
[INFO] 2026-06-22 22:22:53,941 [RapidOCR] base.py:22: Using engine_name: torch
[INFO] 2026-06-22 22:22:53,942 [RapidOCR] device_config.py:64: Using GPU device with ID: 0
[INFO] 2026-06-22 22:22:53,949 [RapidOCR] download_file.py:60: File exists and is valid: /home/creo/coding/Internship/Oncology_Research_Assistant/.venv/lib/python3.12/site-packages/rapidocr/models/ch_ptocr_mobile_v2.0_cls_mobile.pth
[INFO] 2026-06-22 22:22:53,950 [RapidOCR] main.py:50: Using /home/creo/coding/Internship/Oncology_Research_Assistant/.venv/lib/python3.12/site-packages/rapidocr/models/ch_ptocr_mobile_v2.0_cls_mobile.pth

Running Docling (Local Document Parsing)...

[INFO] 2026-06-22 22:22:54,002 [RapidOCR] base.py:22: Using engine_name: torch
[INFO] 2026-06-22 22:22:54,003 [RapidOCR] device_config.py:64: Using GPU device with ID: 0
[INFO] 2026-06-22 22:22:54,050 [RapidOCR] download_file.py:60: File exists and is valid: /home/creo/coding/Internship/Oncology_Research_Assistant/.venv/lib/python3.12/site-packages/rapidocr/models/ch_PP-OCRv4_rec_mobile.pth
[INFO] 2026-06-22 22:22:54,050 [RapidOCR] main.py:50: Using /home/creo/coding/Internship/Oncology_Research_Assistant/.venv/lib/python3.12/site-packages/rapidocr/models/ch_PP-OCRv4_rec_mobile.pth

Loading weights:   0%|          | 0/770 [00:00<?, ?it/s]

Running LlamaParse (Cloud Vision API)...
Started parsing the file under job_id 5db005f6-9bde-4b36-a4f6-7ff76df5f8ad

       Method  Time (s)  Chunks
0     PyMuPDF      0.25     148
1     Docling     29.20    2906
2  LlamaParse     23.42    1883

--- SAMPLE DOCLING EXTRACTION ---
| Gene   | Breast Cancer Risk and Management (First primary)                                                                                                                                                                                                  | Epithelial Ovarian Cancer Risk and Management                                                                                                                                                                                                      | Pancreatic Cancer Risk and Management 13-22 and Other Cancer Risks                                                                                                                                                                                                                      |
|--------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| ATM    | • Absolute risk: 20%-40% 3,4,5,6 • Management: b  Screening: Annual mammogram at age 40 y and consider breast MRI with contrast starting at age 30-35 y c,d,e  Risk reduction: Evidence insufficient for risk- reducing mastectomy (RRM), manage based on family history • Strength of evidence of association with cancer: Strong                                                                                                                                                                                                                                                    | • Absolute risk: 2%-3% 10-12 • Management: f  Risk reduction: Evidence insufficient for risk-reducing salpingo oophorectomy (RRSO); manage based on family history • Strength of evidence of association with cancer: Strong                                                                                                                                                                                                                                                    | Pancreatic cancer • Absolute risk: ~5%-10% g,23 • Management: Screen P/LP variant carriers with a family history of pancreatic cancer, see PANC-A. • Strength of evidence of association with cancer: Strong Prostate cancer • Emerging evidence for association with increased risk 24 |
| ATM    | Comments: Heterozygous ATM P/LP variants should not lead to a recommendation to avoid radiation therapy at this time. See Discussion for information regarding the c.7271T>G variant. See GENE-B for reproductive implications/ recessive disease. | Comments: Heterozygous ATM P/LP variants should not lead to a recommendation to avoid radiation therapy at this time. See Discussion for information regarding the c.7271T>G variant. See GENE-B for reproductive implications/ recessive disease. | Comments: Heterozygous ATM P/LP variants should not lead to a recommendation to avoid radiation therapy at this time. See Discussion for information regarding the c.7271T>G variant. See GENE-B for reproductive implications/ recessive disease.                                      |
| BARD1  | • Absolute risk: 20%-40% 7 • Management:  Screening: Annual mammogram and consider breast MRI with contrast starting at age 40 y c,d,e  Risk reduction: Evidence insufficient for RRM, manage based on family history • Strength of evidence of association with cancer: Strong 7-9                                                                                                                                                                                                                                                    | Evidence of increased risk: No established association                                                                                                                                                                                             | Other cancers • Unknown or insufficient evidence                                                                                                                                                                                                                                        |

In [8]:
import json

# Export the Docling chunks to a local JSON file
output_path = "nccn_parsed_corpus.json"

# Convert Pydantic models to standard dictionaries for JSON saving
serialized_chunks = [chunk.model_dump() for chunk in docling_results["chunks"]]

with open(output_path, "w", encoding="utf-8") as f:
    json.dump(serialized_chunks, f, indent=2)

print(f"Successfully saved {len(serialized_chunks)} chunks to {output_path}")

Successfully saved 2906 chunks to nccn_parsed_corpus.json

In [19]:
type(serialized_chunks)

list

In [27]:
print(serialized_chunks[0])

{'text': 'NCCN Clinical Practice Guidelines in Oncology (NCCN Guidelines ® )', 'metadata': {'source': 'NCCN_Guidelines_dataset/guidelines/2023genetics_bop_3.2023_active_021323.pdf', 'page': 1, 'document_type': 'Clinical Guideline', 'publication_date': '2023', 'section': 'Standard Text', 'chunk_id': '2a57a171-4b15-4b2c-a962-2e4ab4626406'}}

In [28]:
for chunk in serialized_chunks[:10]:
    print(chunk['text'])
    print("=" * 50)
    print(chunk['metadata'])
    print("\n")

NCCN Clinical Practice Guidelines in Oncology (NCCN Guidelines ® )
==================================================
{'source': 'NCCN_Guidelines_dataset/guidelines/2023genetics_bop_3.2023_active_021323.pdf', 'page': 1, 'document_type': 'Clinical Guideline', 'publication_date': '2023', 'section': 'Standard Text', 'chunk_id': '2a57a171-4b15-4b2c-a962-2e4ab4626406'}


Genetic/Familial High-Risk Assessment: Breast, Ovarian, and Pancreatic
==================================================
{'source': 'NCCN_Guidelines_dataset/guidelines/2023genetics_bop_3.2023_active_021323.pdf', 'page': 1, 'document_type': 'Clinical Guideline', 'publication_date': '2023', 'section': 'Standard Text', 'chunk_id': 'db125ef8-bb24-46f4-a378-8555ef42107a'}


Version 3.2023 - February 13, 2023
==================================================
{'source': 'NCCN_Guidelines_dataset/guidelines/2023genetics_bop_3.2023_active_021323.pdf', 'page': 1, 'document_type': 'Clinical Guideline', 'publication_date': '2023', 'section': 'Standard Text', 'chunk_id': 'ff9449cd-0697-4fcb-aa2d-fe6dd20389e8'}


NCCN.org
==================================================
{'source': 'NCCN_Guidelines_dataset/guidelines/2023genetics_bop_3.2023_active_021323.pdf', 'page': 1, 'document_type': 'Clinical Guideline', 'publication_date': '2023', 'section': 'Standard Text', 'chunk_id': 'd4b221d3-e7d0-4529-911b-865e7a24e068'}


Continue
==================================================
{'source': 'NCCN_Guidelines_dataset/guidelines/2023genetics_bop_3.2023_active_021323.pdf', 'page': 1, 'document_type': 'Clinical Guideline', 'publication_date': '2023', 'section': 'Standard Text', 'chunk_id': '71dfe07e-e4a4-4f05-8fbf-7b404f6b1c77'}


Version 3.2023, 02/13/23 © 2023 National Comprehensive Cancer Network ®  (NCCN ® ), All rights reserved. NCCN Guidelines ®  and this illustration may not be reproduced in any form without the express written permission of NCCN.
==================================================
{'source': 'NCCN_Guidelines_dataset/guidelines/2023genetics_bop_3.2023_active_021323.pdf', 'page': 1, 'document_type': 'Clinical Guideline', 'publication_date': '2023', 'section': 'Standard Text', 'chunk_id': 'a8f8dfce-335c-45f1-bb9e-7ddc8429ff4e'}


NCCN Guidelines Index Table of Contents Discussion
==================================================
{'source': 'NCCN_Guidelines_dataset/guidelines/2023genetics_bop_3.2023_active_021323.pdf', 'page': 2, 'document_type': 'Clinical Guideline', 'publication_date': '2023', 'section': 'Standard Text', 'chunk_id': '3559c7e2-c3f1-4385-b702-280da8caefbc'}


*Mary B. Daly, MD, PhD/Chair † ₪
==================================================
{'source': 'NCCN_Guidelines_dataset/guidelines/2023genetics_bop_3.2023_active_021323.pdf', 'page': 2, 'document_type': 'Clinical Guideline', 'publication_date': '2023', 'section': 'Standard Text', 'chunk_id': 'a0584dac-eb14-434b-b406-5d50a01a7212'}


Fox Chase Cancer Center
==================================================
{'source': 'NCCN_Guidelines_dataset/guidelines/2023genetics_bop_3.2023_active_021323.pdf', 'page': 2, 'document_type': 'Clinical Guideline', 'publication_date': '2023', 'section': 'Standard Text', 'chunk_id': '2c84d3c2-ef81-480f-a95d-e066aaf6827b'}


*Tuya Pal, MD/Vice-Chair ₪
==================================================
{'source': 'NCCN_Guidelines_dataset/guidelines/2023genetics_bop_3.2023_active_021323.pdf', 'page': 2, 'document_type': 'Clinical Guideline', 'publication_date': '2023', 'section': 'Standard Text', 'chunk_id': 'fbd27d82-4ae8-46cc-a642-17026c779140'}

In [29]:
class AdvancedIngestionPipeline:
    def __init__(self):
        # Initialize Docling for local structural and tabular parsing
        self.docling_converter = DocumentConverter()
        
        # Initialize LlamaParse requesting strict markdown output
        self.llama_parser = LlamaParse(
            result_type="markdown",
            verbose=True
        )

    def process_pymupdf(self, file_path: str, year: str) -> dict:
        """Baseline extraction: Fast, but loses complex table relationships."""
        start_time = time.time()
        doc = fitz.open(file_path)
        chunks = []
        
        for page_num, page in enumerate(doc):
            text = page.get_text("text").strip()
            if text:
                meta = NCCNChunkMetadata(
                    source=file_path, 
                    page=page_num + 1,
                    publication_date=year
                )
                chunks.append(DocumentChunk(text=text, metadata=meta))
                
        return {
            "method": "PyMuPDF", 
            "time_seconds": time.time() - start_time, 
            "chunks": chunks
        }

    def process_docling(self, file_path: str, year: str, target_chunk_size: int = 800, overlap: int = 150) -> dict:
        """Advanced local extraction: Aggregates tiny blocks, applies overlap, filters noise."""
        start_time = time.time()
        result = self.docling_converter.convert(file_path)
        
        raw_chunks = []
        
        # Extract Tables as Markdown 
        for table in result.document.tables:
            meta = NCCNChunkMetadata(
                source=file_path, 
                page=table.prov[0].page_no if table.prov else 0,
                publication_date=year, 
                section="Tabular Data"
            )
            raw_chunks.append(DocumentChunk(
                text=table.export_to_markdown(doc=result.document), 
                metadata=meta
            ))

        # Extract and Aggregate Standard Text
        current_text_buffer = []
        current_char_count = 0
        current_page = 1

        noise_filters = ["nccn.org", "continue", "table of contents", "discussion", "index", "all rights reserved"]

        for item in result.document.texts:
            text_snippet = item.text.strip()
            if not text_snippet:
                continue
                
            if any(noise in text_snippet.lower() for noise in noise_filters):
                continue

            item_page = item.prov[0].page_no if item.prov else current_page

            if current_char_count >= target_chunk_size or (item_page != current_page and current_text_buffer):
                combined_text = " ".join(current_text_buffer)
                
                if len(combined_text) > 120:
                    meta = NCCNChunkMetadata(
                        source=file_path, 
                        page=current_page,
                        publication_date=year, 
                        section="Aggregated Clinical Prose"
                    )
                    raw_chunks.append(DocumentChunk(text=combined_text, metadata=meta))

                words = combined_text.split()
                overlap_words = words[-max(1, int(len(words)*0.15)):] 
                current_text_buffer = [" ".join(overlap_words)] if overlap_words else []
                current_char_count = len(current_text_buffer[0]) if current_text_buffer else 0

            current_text_buffer.append(text_snippet)
            current_char_count += len(text_snippet) + 1
            current_page = item_page

        if current_text_buffer:
            combined_text = " ".join(current_text_buffer)
            if len(combined_text) > 120:
                meta = NCCNChunkMetadata(source=file_path, page=current_page, publication_date=year, section="Aggregated Clinical Prose")
                raw_chunks.append(DocumentChunk(text=combined_text, metadata=meta))

        return {
            "method": "Docling", 
            "time_seconds": time.time() - start_time, 
            "chunks": raw_chunks
        }

    def process_llamaparse(self, file_path: str, year: str) -> dict:
        """API-based extraction: Premium structural and table parsing via cloud vision models."""
        if "LLAMA_CLOUD_API_KEY" not in os.environ:
            print("Skipping LlamaParse: API Key not set in environment variables.")
            return {"method": "LlamaParse", "time_seconds": 0, "chunks": []}

        start_time = time.time()
        
        documents = self.llama_parser.load_data(file_path)
        chunks = []
        
        for doc in documents:
            blocks = doc.text.split('\n\n')
            for block in blocks:
                if block.strip():
                    meta = NCCNChunkMetadata(
                        source=file_path, 
                        page=0, 
                        publication_date=year, 
                        section="LlamaParse Block"
                    )
                    chunks.append(DocumentChunk(text=block.strip(), metadata=meta))
                    
        return {
            "method": "LlamaParse", 
            "time_seconds": time.time() - start_time, 
            "chunks": chunks
        }

In [30]:
# Set your LlamaCloud API Key if testing LlamaParse
os.environ["LLAMA_CLOUD_API_KEY"] = "llx-GTFHiS8J2S5fceKJDS6VPFfOmHcnopNtsZFkM4QBI7yoO16O"

TEST_FILE = "NCCN_Guidelines_dataset/guidelines/2023genetics_bop_3.2023_active_021323.pdf" 
YEAR = "2023"

pipeline = AdvancedIngestionPipeline()

print(f"Running PyMuPDF...")
pymupdf_results = pipeline.process_pymupdf(TEST_FILE, YEAR)

print("Running Docling (Local Document Parsing)...")
docling_results = pipeline.process_docling(TEST_FILE, YEAR)

print("Running LlamaParse (Cloud Vision API)...")
llamaparse_results = pipeline.process_llamaparse(TEST_FILE, YEAR)

# Generate Benchmark Report
df_report = pd.DataFrame([
    {"Method": "PyMuPDF", "Time (s)": round(pymupdf_results["time_seconds"], 2), "Chunks": len(pymupdf_results["chunks"])},
    {"Method": "Docling", "Time (s)": round(docling_results["time_seconds"], 2), "Chunks": len(docling_results["chunks"])},
    {"Method": "LlamaParse", "Time (s)": round(llamaparse_results["time_seconds"], 2), "Chunks": len(llamaparse_results["chunks"])}
])

display(df_report)

# Inspect output to verify table structures
print("\n--- SAMPLE DOCLING EXTRACTION ---")
if docling_results["chunks"]:
    table_chunks = [c for c in docling_results["chunks"] if c.metadata.section == "Tabular Data"]
    if table_chunks:
        print(table_chunks[0].text)

Running PyMuPDF...
Running Docling (Local Document Parsing)...

[INFO] 2026-06-22 22:57:48,907 [RapidOCR] base.py:22: Using engine_name: torch
[INFO] 2026-06-22 22:57:48,908 [RapidOCR] device_config.py:64: Using GPU device with ID: 0
[INFO] 2026-06-22 22:57:48,931 [RapidOCR] download_file.py:60: File exists and is valid: /home/creo/coding/Internship/Oncology_Research_Assistant/.venv/lib/python3.12/site-packages/rapidocr/models/ch_PP-OCRv4_det_mobile.pth
[INFO] 2026-06-22 22:57:48,931 [RapidOCR] main.py:50: Using /home/creo/coding/Internship/Oncology_Research_Assistant/.venv/lib/python3.12/site-packages/rapidocr/models/ch_PP-OCRv4_det_mobile.pth
[INFO] 2026-06-22 22:57:49,059 [RapidOCR] base.py:22: Using engine_name: torch
[INFO] 2026-06-22 22:57:49,059 [RapidOCR] device_config.py:64: Using GPU device with ID: 0
[INFO] 2026-06-22 22:57:49,062 [RapidOCR] download_file.py:60: File exists and is valid: /home/creo/coding/Internship/Oncology_Research_Assistant/.venv/lib/python3.12/site-packages/rapidocr/models/ch_ptocr_mobile_v2.0_cls_mobile.pth
[INFO] 2026-06-22 22:57:49,062 [RapidOCR] main.py:50: Using /home/creo/coding/Internship/Oncology_Research_Assistant/.venv/lib/python3.12/site-packages/rapidocr/models/ch_ptocr_mobile_v2.0_cls_mobile.pth
[INFO] 2026-06-22 22:57:49,107 [RapidOCR] base.py:22: Using engine_name: torch
[INFO] 2026-06-22 22:57:49,108 [RapidOCR] device_config.py:64: Using GPU device with ID: 0
[INFO] 2026-06-22 22:57:49,152 [RapidOCR] download_file.py:60: File exists and is valid: /home/creo/coding/Internship/Oncology_Research_Assistant/.venv/lib/python3.12/site-packages/rapidocr/models/ch_PP-OCRv4_rec_mobile.pth
[INFO] 2026-06-22 22:57:49,152 [RapidOCR] main.py:50: Using /home/creo/coding/Internship/Oncology_Research_Assistant/.venv/lib/python3.12/site-packages/rapidocr/models/ch_PP-OCRv4_rec_mobile.pth

Loading weights:   0%|          | 0/770 [00:00<?, ?it/s]

Running LlamaParse (Cloud Vision API)...
Started parsing the file under job_id 5db005f6-9bde-4b36-a4f6-7ff76df5f8ad

       Method  Time (s)  Chunks
0     PyMuPDF      0.26     148
1     Docling     31.90     622
2  LlamaParse     10.31    1883

--- SAMPLE DOCLING EXTRACTION ---
| Gene   | Breast Cancer Risk and Management (First primary)                                                                                                                                                                                                  | Epithelial Ovarian Cancer Risk and Management                                                                                                                                                                                                      | Pancreatic Cancer Risk and Management 13-22 and Other Cancer Risks                                                                                                                                                                                                                      |
|--------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| ATM    | • Absolute risk: 20%-40% 3,4,5,6 • Management: b  Screening: Annual mammogram at age 40 y and consider breast MRI with contrast starting at age 30-35 y c,d,e  Risk reduction: Evidence insufficient for risk- reducing mastectomy (RRM), manage based on family history • Strength of evidence of association with cancer: Strong                                                                                                                                                                                                                                                    | • Absolute risk: 2%-3% 10-12 • Management: f  Risk reduction: Evidence insufficient for risk-reducing salpingo oophorectomy (RRSO); manage based on family history • Strength of evidence of association with cancer: Strong                                                                                                                                                                                                                                                    | Pancreatic cancer • Absolute risk: ~5%-10% g,23 • Management: Screen P/LP variant carriers with a family history of pancreatic cancer, see PANC-A. • Strength of evidence of association with cancer: Strong Prostate cancer • Emerging evidence for association with increased risk 24 |
| ATM    | Comments: Heterozygous ATM P/LP variants should not lead to a recommendation to avoid radiation therapy at this time. See Discussion for information regarding the c.7271T>G variant. See GENE-B for reproductive implications/ recessive disease. | Comments: Heterozygous ATM P/LP variants should not lead to a recommendation to avoid radiation therapy at this time. See Discussion for information regarding the c.7271T>G variant. See GENE-B for reproductive implications/ recessive disease. | Comments: Heterozygous ATM P/LP variants should not lead to a recommendation to avoid radiation therapy at this time. See Discussion for information regarding the c.7271T>G variant. See GENE-B for reproductive implications/ recessive disease.                                      |
| BARD1  | • Absolute risk: 20%-40% 7 • Management:  Screening: Annual mammogram and consider breast MRI with contrast starting at age 40 y c,d,e  Risk reduction: Evidence insufficient for RRM, manage based on family history • Strength of evidence of association with cancer: Strong 7-9                                                                                                                                                                                                                                                    | Evidence of increased risk: No established association                                                                                                                                                                                             | Other cancers • Unknown or insufficient evidence                                                                                                                                                                                                                                        |

In [31]:
import json

# Export the Docling chunks to a local JSON file
output_path = "nccn_parsed_corpus.json"

# Convert Pydantic models to standard dictionaries for JSON saving
serialized_chunks = [chunk.model_dump() for chunk in docling_results["chunks"]]

with open(output_path, "w", encoding="utf-8") as f:
    json.dump(serialized_chunks, f, indent=2)

print(f"Successfully saved {len(serialized_chunks)} chunks to {output_path}")

Successfully saved 622 chunks to nccn_parsed_corpus.json

In [32]:
for chunk in serialized_chunks[:10]:
    print(chunk['text'])
    print("=" * 50)
    print(chunk['metadata'])
    print("\n")

| Gene   | Breast Cancer Risk and Management (First primary)                                                                                                                                                                                                  | Epithelial Ovarian Cancer Risk and Management                                                                                                                                                                                                      | Pancreatic Cancer Risk and Management 13-22 and Other Cancer Risks                                                                                                                                                                                                                      |
|--------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| ATM    | • Absolute risk: 20%-40% 3,4,5,6 • Management: b  Screening: Annual mammogram at age 40 y and consider breast MRI with contrast starting at age 30-35 y c,d,e  Risk reduction: Evidence insufficient for risk- reducing mastectomy (RRM), manage based on family history • Strength of evidence of association with cancer: Strong                                                                                                                                                                                                                                                    | • Absolute risk: 2%-3% 10-12 • Management: f  Risk reduction: Evidence insufficient for risk-reducing salpingo oophorectomy (RRSO); manage based on family history • Strength of evidence of association with cancer: Strong                                                                                                                                                                                                                                                    | Pancreatic cancer • Absolute risk: ~5%-10% g,23 • Management: Screen P/LP variant carriers with a family history of pancreatic cancer, see PANC-A. • Strength of evidence of association with cancer: Strong Prostate cancer • Emerging evidence for association with increased risk 24 |
| ATM    | Comments: Heterozygous ATM P/LP variants should not lead to a recommendation to avoid radiation therapy at this time. See Discussion for information regarding the c.7271T>G variant. See GENE-B for reproductive implications/ recessive disease. | Comments: Heterozygous ATM P/LP variants should not lead to a recommendation to avoid radiation therapy at this time. See Discussion for information regarding the c.7271T>G variant. See GENE-B for reproductive implications/ recessive disease. | Comments: Heterozygous ATM P/LP variants should not lead to a recommendation to avoid radiation therapy at this time. See Discussion for information regarding the c.7271T>G variant. See GENE-B for reproductive implications/ recessive disease.                                      |
| BARD1  | • Absolute risk: 20%-40% 7 • Management:  Screening: Annual mammogram and consider breast MRI with contrast starting at age 40 y c,d,e  Risk reduction: Evidence insufficient for RRM, manage based on family history • Strength of evidence of association with cancer: Strong 7-9                                                                                                                                                                                                                                                    | Evidence of increased risk: No established association                                                                                                                                                                                             | Other cancers • Unknown or insufficient evidence                                                                                                                                                                                                                                        |
==================================================
{'source': 'NCCN_Guidelines_dataset/guidelines/2023genetics_bop_3.2023_active_021323.pdf', 'page': 35, 'document_type': 'Clinical Guideline', 'publication_date': '2023', 'section': 'Tabular Data', 'chunk_id': 'ff0ca2da-ea58-47e3-9b9e-f530292dc480'}


| Gene   | Breast Cancer Risk and Management (First primary)                                                                                                                                                                                                                                                                                      | Epithelial Ovarian Cancer Risk and Management                                                                                                            | Pancreatic Cancer Risk and Management 13-22 and Other Cancer Risks                                                                                                                                                                                                                                                                                                                     |
|--------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| BRCA1  | • Absolute risk: >60% 5,25-29 • Management: See BRCA Pathogenic Variant- Positive Management • Strength of evidence of association with cancer: Very strong (with predisposition to triple-negative disease) Male breast cancer • Absolute risk: 0.2%-1.2% by age 70 y 30,31 • Strength of evidence of association with cancer: Strong | • Absolute risk: 39%-58% 33 • Management: See BRCA Pathogenic Variant-Positive Management • Strength of evidence of association with cancer: Very strong | Pancreatic cancer • Absolute risk: ≤5% 31 • Management: Screen P/LP variant carriers with a family history of pancreatic cancer, see PANC-A. • Strength of evidence of association with cancer: Strong Prostate cancer • Absolute risk: 7%-26% 34 • Management: See BRCA Pathogenic Variant-Positive Management                                                                        |
|        | Comment: See GENE-B for reproductive implications/ recessive disease.                                                                                                                                                                                                                                                                  | Comment: See GENE-B for reproductive implications/ recessive disease.                                                                                    | Comment: See GENE-B for reproductive implications/ recessive disease.                                                                                                                                                                                                                                                                                                                  |
| BRCA2  | • Absolute risk: >60% 5,21-25 • Management: See BRCA Pathogenic Variant- Positive Management • Strength of evidence of association with cancer: Very strong Male breast cancer • Absolute risk: 1.8%-7.1% by age 70 y 30,31,32 • Strength of evidence of association with cancer: Strong                                               | • Absolute risk: 13%-29% 33 • Management: See BRCA Pathogenic Variant-Positive Management • Strength of evidence of association with cancer: Very strong | Pancreatic cancer • Absolute risk: 5%-10% 31 • Management: Screen P/LP variant carriers with a family history of pancreatic cancer, see PANC-A. • Strength of evidence of association with cancer: Very strong Prostate cancer • Absolute risk: 19%-61% 34,35 • Management: See BRCA Pathogenic Variant-Positive Management Melanoma • See BRCA Pathogenic Variant-Positive Management |
| BRCA2  | Comment: See GENE-B for reproductive implications/ recessive disease.                                                                                                                                                                                                                                                                  | Comment: See GENE-B for reproductive implications/ recessive disease.                                                                                    | Comment: See GENE-B for reproductive implications/ recessive disease.                                                                                                                                                                                                                                                                                                                  |
==================================================
{'source': 'NCCN_Guidelines_dataset/guidelines/2023genetics_bop_3.2023_active_021323.pdf', 'page': 36, 'document_type': 'Clinical Guideline', 'publication_date': '2023', 'section': 'Tabular Data', 'chunk_id': '9a67917f-04fa-4ddb-90b4-91f1635aa85a'}


| Gene   | Breast Cancer Risk and Management (First primary)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                | Epithelial Ovarian Cancer Risk and Management                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    | Pancreatic Cancer Risk and Management 13-22 and Other Cancer Risks                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               |
|--------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| BRIP1  | • Absolute risk: Insufficient data to define • Management: Insufficient data; managed based on family history • Strength of evidence of association with cancer: Limited; potential increase in female breast cancer 8                                                                                                                                                                                                                                                                                                                                                                                                                           | • Absolute risk: 5%-15% 10-12,39 • Management:  Risk reduction: Recommend RRSO at age 45-50 y h • Strength of evidence of association with cancer: Strong                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  | Other cancers • Unknown or insufficient evidence                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
| BRIP1  | Comments: See GENE-B for reproductive implications/ recessive disease. Based on estimates from available studies, the lifetime risk of ovarian cancer in carriers of P/LP variants in BRIP1 appears to be sufficient to justify RRSO. The current evidence is insufficient to make a firm recommendation as to the optimal age for this procedure. Based on the current, limited evidence base, a discussion about surgery should be held around age 45-50 y or earlier based on a specific family history of an earlier onset of ovarian cancer.                                                                                                | Comments: See GENE-B for reproductive implications/ recessive disease. Based on estimates from available studies, the lifetime risk of ovarian cancer in carriers of P/LP variants in BRIP1 appears to be sufficient to justify RRSO. The current evidence is insufficient to make a firm recommendation as to the optimal age for this procedure. Based on the current, limited evidence base, a discussion about surgery should be held around age 45-50 y or earlier based on a specific family history of an earlier onset of ovarian cancer.                                                                                                | Comments: See GENE-B for reproductive implications/ recessive disease. Based on estimates from available studies, the lifetime risk of ovarian cancer in carriers of P/LP variants in BRIP1 appears to be sufficient to justify RRSO. The current evidence is insufficient to make a firm recommendation as to the optimal age for this procedure. Based on the current, limited evidence base, a discussion about surgery should be held around age 45-50 y or earlier based on a specific family history of an earlier onset of ovarian cancer.                                                                                                |